server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-connections: 20000
    accept-count: 1000
    threads:
      max: 1000
      min-spare: 30

spring:
  application:
    name: demo
  messages:
    basename: i18n/messages
  aop:
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization.write-dates-as-timestamps: false

zookeeper:
  connect-string: 127.0.0.1:2181
  base-path: worker_id
  max-retries: 3
  base-sleep-ms: 100
  max-sleep-ms: 1000

worker-id:
  min-id: 0
  max-id: 1000
  group-id: ${spring.application.name}
